In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Import the data set
dataset = pd.read_csv(r"./Practice-data-sets/Data.csv")

In [3]:
dataset

       State   Age   Salary Purchased
0     Mumbai  44.0  72000.0        No
1  Bangalore  27.0  48000.0       Yes
2  Hyderabad  30.0  54000.0        No
3  Bangalore  38.0  61000.0        No
4  Hyderabad  40.0      NaN       Yes
5     Mumbai  35.0  58000.0       Yes
6  Bangalore   NaN  52000.0        No
7     Mumbai  48.0  79000.0       Yes
8  Hyderabad  50.0  83000.0        No
9     Mumbai  37.0  67000.0       Yes

In [4]:
#Split independent variables
dataset.iloc[:,:-1]

       State   Age   Salary
0     Mumbai  44.0  72000.0
1  Bangalore  27.0  48000.0
2  Hyderabad  30.0  54000.0
3  Bangalore  38.0  61000.0
4  Hyderabad  40.0      NaN
5     Mumbai  35.0  58000.0
6  Bangalore   NaN  52000.0
7     Mumbai  48.0  79000.0
8  Hyderabad  50.0  83000.0
9     Mumbai  37.0  67000.0

In [6]:
dataset.iloc[:,:-1].values # converts into an array

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, nan],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', nan, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [10]:
X = dataset.iloc[:,:-1].values

In [11]:
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, nan],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', nan, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [12]:
type(X)

numpy.ndarray

In [13]:
# Dependent attribute
Y = dataset.iloc[:, 3].values

In [14]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [15]:
## DONE SO FAR: Now, have Independent and dependent variables separately

In [16]:
# Using SKLearn imputation concept to fill numerical values

In [17]:
from sklearn.impute import SimpleImputer

In [18]:
imputer = SimpleImputer() # created an object

In [19]:
X[0]

array(['Mumbai', 44.0, 72000.0], dtype=object)

In [20]:
X[:,0]

array(['Mumbai', 'Bangalore', 'Hyderabad', 'Bangalore', 'Hyderabad',
       'Mumbai', 'Bangalore', 'Mumbai', 'Hyderabad', 'Mumbai'],
      dtype=object)

In [22]:
imputer = imputer.fit(X[:,1:3])

In [23]:
X[:,1:3] = imputer.transform(X[:,1:3])

In [24]:
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, 63777.77777777778],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', 38.77777777777778, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [25]:
# Using label encoder for target variables

In [26]:
from sklearn.preprocessing import LabelEncoder

In [31]:
label_encoder_x = LabelEncoder()

In [32]:
X

array([['Mumbai', 44.0, 72000.0],
       ['Bangalore', 27.0, 48000.0],
       ['Hyderabad', 30.0, 54000.0],
       ['Bangalore', 38.0, 61000.0],
       ['Hyderabad', 40.0, 63777.77777777778],
       ['Mumbai', 35.0, 58000.0],
       ['Bangalore', 38.77777777777778, 52000.0],
       ['Mumbai', 48.0, 79000.0],
       ['Hyderabad', 50.0, 83000.0],
       ['Mumbai', 37.0, 67000.0]], dtype=object)

In [35]:
# IMPUTE for Categorical data - independent type
X[:,0] = label_encoder_x.fit_transform(X[:,0])

In [36]:
X

array([[2, 44.0, 72000.0],
       [0, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [0, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [2, 35.0, 58000.0],
       [0, 38.77777777777778, 52000.0],
       [2, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [2, 37.0, 67000.0]], dtype=object)

In [37]:
label_encoder_y = LabelEncoder()

In [39]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [40]:
Y = label_encoder_y.fit_transform(Y)

In [41]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [42]:
#SPLIT THE DATA

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [45]:
X_test

array([[1, 30.0, 54000.0],
       [2, 37.0, 67000.0]], dtype=object)

In [46]:
X_train

array([[0, 38.77777777777778, 52000.0],
       [1, 40.0, 63777.77777777778],
       [2, 44.0, 72000.0],
       [0, 38.0, 61000.0],
       [0, 27.0, 48000.0],
       [2, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [2, 35.0, 58000.0]], dtype=object)

In [47]:
# Normalise

In [48]:
from sklearn.preprocessing import Normalizer
sc_x = Normalizer()

In [49]:
X_train = sc_x.fit_transform(X_train)

In [50]:
X_train

array([[0.00000000e+00, 7.45726288e-04, 9.99999722e-01],
       [1.56794394e-05, 6.27177577e-04, 9.99999803e-01],
       [2.77777726e-05, 6.11110997e-04, 9.99999813e-01],
       [0.00000000e+00, 6.22950699e-04, 9.99999806e-01],
       [0.00000000e+00, 5.62499911e-04, 9.99999842e-01],
       [2.53164510e-05, 6.07594824e-04, 9.99999815e-01],
       [1.20481906e-05, 6.02409529e-04, 9.99999818e-01],
       [3.44827523e-05, 6.03448166e-04, 9.99999817e-01]])

In [51]:
X_test

array([[1, 30.0, 54000.0],
       [2, 37.0, 67000.0]], dtype=object)

In [52]:
X_test = sc_x.fit_transform(X_test)

In [53]:
X_test

array([[1.85185157e-05, 5.55555470e-04, 9.99999846e-01],
       [2.98507417e-05, 5.52238722e-04, 9.99999847e-01]])